package com.james.tax.ui;

import com.james.tax.TaxPropsProvider;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

/**
 * @author jianxuezhang
 * @date 2022/10/13
 */
public class SettingFormUI {
    private JPanel panel1;
    private JTextArea textArea1;
    private JButton 保存Button;
    static JFrame frame = new JFrame("设置");

    public SettingFormUI() {
        保存Button.addActionListener(e -> {
            TaxPropsProvider.storeData(textArea1.getText());
            TaxPropsProvider.reload();
            frame.dispose();
        });
    }

    public static final void openSetting(JFrame mainFrame) {
        SettingFormUI settingFormUI = new SettingFormUI();
        frame.setContentPane(settingFormUI.panel1);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(500, 400);
        frame.setResizable(false);
        settingFormUI.createContent();
        frame.setLocationRelativeTo(mainFrame);
        frame.setAlwaysOnTop(true);
        frame.setVisible(true);
    }

    private void createContent() {
        textArea1.setText(TaxPropsProvider.showData());

    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("SettingFormUI");
        frame.setContentPane(new SettingFormUI().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.setBackground(new Color(-1117475));
        final JLabel label1 = new JLabel();
        label1.setText("");
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xy(3, 1));
        final JLabel label2 = new JLabel();
        label2.setText("配置参数");
        panel1.add(label2, cc.xy(3, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setVerticalScrollBarPolicy(22);
        panel1.add(scrollPane1, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.FILL));
        textArea1 = new JTextArea();
        scrollPane1.setViewportView(textArea1);
        保存Button = new JButton();
        保存Button.setText("保存");
        panel1.add(保存Button, cc.xy(3, 7, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
