package com.james.tax.ui;

import com.james.tax.TaxCalculateMain;
import com.james.tax.util.LogUtil;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.concurrent.TimeUnit;

/**
 * @author jianxuezhang
 * @date 2022/10/12
 */
public class TaxCalculateUIMain {
    private JPanel panel1;
    private JButton 计算Button;
    private JButton 设置Button;
    private JButton 关于Button;
    private JButton 清屏Button;
    private JTextArea textArea1;
    private JButton 设置Button1;
    private JProgressBar progressBar1;
    static JFrame frame = new JFrame("个税计算器");

    public TaxCalculateUIMain() {
        计算Button.addActionListener(e -> {
            LogUtil.removeLog();
            TaxCalculateMain.calc();
            String data = LogUtil.getLog();
            progressBar1.setValue(0);
            new Thread(() -> {
                for (int i = 1; i <= 10; i++) {
                    try {
                        TimeUnit.MILLISECONDS.sleep(50);
                        progressBar1.setValue(i * 10);
                    } catch (InterruptedException e1) {
                        e1.printStackTrace();
                    }
                }
                //progressBar1.setIndeterminate(true);
                //progressBar1.setStringPainted(true);
                textArea1.append(data);

            }).start();

        });
        关于Button.addActionListener(e -> JOptionPane.showMessageDialog(TaxCalculateUIMain.this.panel1, "个税计算器\r\nCopyright 2022 mailto:zjx_io@163.com All Right Reserved!"));
        清屏Button.addActionListener(e -> textArea1.setText(""));
        设置Button.addActionListener(e -> SettingFormUI.openSetting(null));
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int ret = JOptionPane.showInternalConfirmDialog(panel1, "确定要关闭么?", "提示", JOptionPane.YES_NO_OPTION);
                if (ret == JOptionPane.YES_OPTION) {
                    frame.dispose();
                    System.exit(0);
                }
            }

        });
    }

    public static void main(String[] args) {
       /* try {
            BeautyEyeLNFHelper.launchBeautyEyeLNF();
        } catch (Exception e) {
            //TODO exception
        }*/
        frame.setContentPane(new TaxCalculateUIMain().panel1);
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        frame.setResizable(false);
        //frame.pack();
        frame.setSize(500, 400);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:16dlu:noGrow,fill:57px:grow,left:10dlu:noGrow,fill:69px:grow,left:12dlu:noGrow,fill:47px:grow,left:5dlu:noGrow,fill:29px:noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:8dlu:noGrow,top:10dlu:noGrow,top:10dlu:noGrow,center:205px:noGrow,top:13dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.setBackground(new Color(-1117475));
        计算Button = new JButton();
        计算Button.setText("计算");
        CellConstraints cc = new CellConstraints();
        panel1.add(计算Button, cc.xy(3, 3));
        设置Button = new JButton();
        设置Button.setText("设置");
        panel1.add(设置Button, cc.xy(5, 3));
        关于Button = new JButton();
        关于Button.setText("关于");
        panel1.add(关于Button, cc.xyw(7, 3, 2));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setVerticalScrollBarPolicy(22);
        panel1.add(scrollPane1, cc.xyw(3, 7, 6, CellConstraints.FILL, CellConstraints.FILL));
        textArea1 = new JTextArea();
        scrollPane1.setViewportView(textArea1);
        清屏Button = new JButton();
        清屏Button.setText("清屏");
        panel1.add(清屏Button, cc.xy(5, 9));
        final JLabel label1 = new JLabel();
        label1.setText("计算结果");
        panel1.add(label1, cc.xywh(5, 4, 1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        progressBar1 = new JProgressBar();
        progressBar1.setIndeterminate(false);
        progressBar1.setStringPainted(true);
        panel1.add(progressBar1, cc.xyw(7, 9, 2, CellConstraints.FILL, CellConstraints.CENTER));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
